"use client";
import { ChevronDown } from "lucide-react";
import { AnimatePresence,motion } from "framer-motion";
import { useState } from "react";
import { Container } from "@/components/layout/Container";
import { SectionWrapper } from "@/components/layout/SectionWrapper";
import { SectionLabel } from "@/components/layout/SectionLabel";
const faqs=[['How do projects usually start?','We start with the workflow and the outcome, not the tool. A short discovery conversation turns the idea into a scoped build.'],['How long does a project take?','Small builds can move quickly; larger systems depend on integrations, data, testing, and feedback. The scope determines the schedule.'],['Can you work with tools I already use?','Yes. Existing APIs, webhooks, databases, and automation platforms can often be connected instead of replaced.'],['Can I request revisions?','Yes. Each engagement defines a clear revision and feedback cycle so the process stays predictable.'],['Do you build only AI features?','No. The focus is useful systems: AI where it adds value, automation where it removes friction, and normal software everywhere else.']];
export function FAQ(){const [open,setOpen]=useState<number|null>(null);return <SectionWrapper id="faq"><Container size="small"><SectionLabel text="FAQ"/><h2 className="mt-5 text-4xl font-bold md:text-5xl">Common <span className="text-gradient">Questions</span></h2><div className="mt-10 divide-y divide-white/10 rounded-2xl border border-white/10 bg-slate-900/40">{faqs.map(([q,a],i)=><div key={q} className="p-5"><button onClick={()=>setOpen(open===i?null:i)} className="flex w-full items-center justify-between text-left"><span className="font-semibold text-white">{q}</span><motion.span animate={{rotate:open===i?180:0}}><ChevronDown size={18}/></motion.span></button><AnimatePresence>{open===i?<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><p className="pt-4 text-sm leading-7 text-slate-400">{a}</p></motion.div>:null}</AnimatePresence></div>)}</div></Container></SectionWrapper>}
