"use client";
import Link from "next/link";
import { ChevronDown, Sparkles } from "lucide-react";
import { motion } from "framer-motion";
import { MeshGradient } from "@/components/animations/MeshGradient";
import { ParticleBackground } from "@/components/animations/ParticleBackground";
import { Typewriter } from "@/components/animations/Typewriter";
import { SectionLabel } from "@/components/layout/SectionLabel";
import { MagneticButton } from "@/components/animations/MagneticButton";
import { useSiteSettings } from "@/hooks/useSiteSettings";
export function Hero(){const {settings}=useSiteSettings();if(!settings.sections.hero)return null;return <section className="relative flex min-h-screen items-center justify-center overflow-hidden px-4 pt-24"><MeshGradient/>{settings.appearance.enableParticles?<ParticleBackground particleCount={78}/>:null}<div className="relative z-10 mx-auto max-w-5xl text-center"><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.2}}><SectionLabel text="AI-POWERED SOLUTIONS" className="justify-center"/></motion.div><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.4,duration:.8}} className="mx-auto mt-7 max-w-5xl text-[clamp(2.5rem,6vw,5.25rem)] font-extrabold leading-[1.05] tracking-[-.03em]"> <Typewriter text="Crafting Digital Experiences" speed={45} /> <span className="block text-gradient">That Matter</span></motion.h1><motion.p initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.6}} className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-400 md:text-xl">Building intelligent digital systems, automation workflows, and polished web platforms — one thoughtful project at a time.</motion.p><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.8}} className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row"><MagneticButton className="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-7 py-4 font-semibold text-slate-950 shadow-glow hover:bg-emerald-400"><Link href="/portfolio">View My Work <Sparkles className="inline" size={17}/></Link></MagneticButton><MagneticButton className="rounded-xl border border-white/15 bg-white/5 px-7 py-4 font-semibold text-white hover:bg-white/10"><Link href="/contact">Get in Touch</Link></MagneticButton></motion.div></div><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:1.6}} className="absolute bottom-7 left-1/2 -translate-x-1/2 text-center text-[10px] uppercase tracking-[.28em] text-slate-500"><ChevronDown className="mx-auto mb-2 animate-bounce" size={18}/><span>Scroll to explore</span></motion.div></section>}
