"use client";
import { AnimatePresence,motion } from "framer-motion";
import { useEffect,useState } from "react";
import { Container } from "@/components/layout/Container";
import { SectionWrapper } from "@/components/layout/SectionWrapper";
import { SectionLabel } from "@/components/layout/SectionLabel";
import { PortfolioFilter } from "@/components/portfolio/PortfolioFilter";
import { PortfolioCard } from "@/components/portfolio/PortfolioCard";
import type { PortfolioItem } from "@/types";
import { ArrowRight } from "lucide-react";
import Link from "next/link";
const fallback:PortfolioItem[]=[{id:"p1",title:"Agentic Research Workspace",location:"Remote",category:"Agentic AI",description:"A modular workspace for research, synthesis, and publishing workflows.",coverImage:"",gallery:[],videoUrl:"",tech:["Next.js","Firebase","Agentic AI"],status:"in_progress",featured:true,date:new Date()},{id:"p2",title:"Lead Operations Dashboard",location:"Remote",category:"Automation",description:"A CRM-style workspace for leads, follow-ups, notes, and reporting.",coverImage:"",gallery:[],videoUrl:"",tech:["Next.js","Firestore","Automation"],status:"complete",featured:true,date:new Date()},{id:"p3",title:"Content Systems Lab",location:"Remote",category:"Automation",description:"A content planning system designed around repeatable creation and publishing flows.",coverImage:"",gallery:[],videoUrl:"",tech:["Next.js","Markdown"],status:"planned",featured:false,date:new Date()}];
export function Portfolio(){const [items,setItems]=useState<PortfolioItem[]>([]);const [active,setActive]=useState("All");useEffect(()=>{fetch("/api/portfolio",{cache:"no-store"}).then(r=>r.ok?r.json():[]).then(d=>setItems(d.length?d:fallback)).catch(()=>setItems(fallback))},[]);const cats=["All",...Array.from(new Set(items.map(p=>p.category)))];const shown=active==="All"?items:items.filter(p=>p.category===active);return <SectionWrapper id="portfolio"><Container><SectionLabel text="PORTFOLIO"/><div className="mt-6 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><h2 className="text-4xl font-bold md:text-5xl">Recent <span className="text-gradient">Work</span></h2><p className="mt-4 max-w-2xl text-slate-400">Systems, interfaces, and experiments that show how the thinking turns into something usable.</p></div><PortfolioFilter categories={cats} active={active} onChange={setActive}/></div><motion.div layout className="mt-10 grid gap-8 md:grid-cols-2"><AnimatePresence mode="popLayout">{shown.map((p,i)=><PortfolioCard key={p.id} project={p} index={i} featured={Boolean(p.featured&&i===0)}/>)}</AnimatePresence></motion.div><div className="mt-10"><Link href="/portfolio" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold text-white hover:bg-white/5">View All Projects <ArrowRight size={16}/></Link></div></Container></SectionWrapper>}
