"use client";
import { Check } from "lucide-react";
import { Container } from "@/components/layout/Container";
import { SectionWrapper } from "@/components/layout/SectionWrapper";
import { SectionLabel } from "@/components/layout/SectionLabel";
import { GlassCard } from "@/components/layout/GlassCard";
import { GlowBorder } from "@/components/animations/GlowBorder";
import { useSiteSettings } from "@/hooks/useSiteSettings";
const fallback=[{id:"starter",name:"Starter",price:"Custom",cadence:"project",description:"A focused build for a clear problem.",features:["Discovery call","Defined scope","Production-ready delivery","1 revision cycle"],cta:"Discuss a Project"},{id:"pro",name:"Professional",price:"Custom",cadence:"project",description:"A complete system with automation and polish.",features:["Everything in Starter","Automation workflows","Admin tooling","Analytics + deployment support"],cta:"Build the System",featured:true},{id:"long-term",name:"Long-term",price:"Custom",cadence:"retainer",description:"Ongoing improvements and new capabilities.",features:["Priority support","Continuous improvements","Architecture guidance","New feature delivery"],cta:"Plan a Retainer"}];
export function Pricing(){const {settings}=useSiteSettings();if(!settings.sections.pricing)return null;const tiers=settings.pricing.tiers.length?settings.pricing.tiers:fallback;return <SectionWrapper id="pricing"><Container><SectionLabel text="PRICING"/><h2 className="mt-5 text-4xl font-bold md:text-5xl">Simple, transparent <span className="text-gradient">pricing</span></h2><p className="mt-4 max-w-2xl text-slate-400">Pricing is based on scope, complexity, integrations, and the amount of ongoing support the system needs.</p><div className="mt-12 grid gap-7 lg:grid-cols-3">{tiers.map(t=>{const card=<div className="p-7"><div className="flex items-center justify-between gap-3"><h3 className="text-2xl font-semibold">{t.name}</h3>{t.featured?<span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-medium text-emerald-300">Featured</span>:null}</div><p className="mt-4 text-3xl font-bold text-white">{t.price}</p><p className="mt-1 text-sm text-slate-500">{t.cadence}</p><p className="mt-5 text-sm leading-7 text-slate-400">{t.description}</p><div className="mt-6 space-y-3">{t.features.map(f=><div key={f} className="flex gap-3 text-sm text-slate-300"><Check size={17} className="mt-0.5 text-emerald-400"/>{f}</div>)}</div><a href="/contact" className="mt-8 block rounded-xl bg-white/5 px-4 py-3 text-center text-sm font-semibold text-white hover:bg-white/10">{t.cta}</a></div>;return t.featured?<GlowBorder key={t.id}>{card}</GlowBorder>:<GlassCard key={t.id}>{card}</GlassCard>})}</div></Container></SectionWrapper>}
