"use client";
import { useEffect,useMemo,useState } from "react";
import { BookOpen } from "lucide-react";
import { Container } from "@/components/layout/Container";
import { SectionLabel } from "@/components/layout/SectionLabel";
import { BlogCard } from "@/components/blog/BlogCard";
import { BlogSearch } from "@/components/blog/BlogSearch";
import type { Post } from "@/types";
import { useDebounce } from "@/hooks/useDebounce";
export default function BlogPage(){const [posts,setPosts]=useState<Post[]>([]);const [q,setQ]=useState("");const [cat,setCat]=useState("All");const [page,setPage]=useState(1);const search=useDebounce(q,200);useEffect(()=>{fetch("/api/posts?limit=100",{cache:"no-store"}).then(r=>r.ok?r.json():[]).then(setPosts).catch(()=>{})},[]);const cats=["All",...Array.from(new Set(posts.map(p=>p.category)))];const filtered=useMemo(()=>posts.filter(p=>(cat==="All"||p.category===cat)&&(!search||`${p.title} ${p.excerpt} ${p.content}`.toLowerCase().includes(search.toLowerCase()))),[posts,cat,search]);const total=Math.max(1,Math.ceil(filtered.length/9));const shown=filtered.slice((page-1)*9,page*9);return <main className="pt-28 pb-20"><Container><SectionLabel text="BLOG"/><h1 className="mt-5 text-5xl font-black md:text-7xl">Insights & <span className="text-gradient">Journey</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-400">Thoughts on AI, automation, software, and the process of learning by shipping.</p><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_290px]"><div><BlogSearch value={q} onChange={v=>{setQ(v);setPage(1)}}/><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{cats.map(c=><button key={c} onClick={()=>{setCat(c);setPage(1)}} className={`whitespace-nowrap rounded-full border px-3 py-1.5 text-xs ${cat===c?"border-emerald-500/50 bg-emerald-500/10 text-emerald-300":"border-white/10 text-slate-400"}`}>{c}</button>)}</div>{shown.length?<div className="mt-7 grid gap-7 md:grid-cols-2">{shown.map((p,i)=><BlogCard key={p.id} post={p} index={i}/>)}</div>:<div className="mt-10"><div className="rounded-2xl border border-white/10 bg-white/[.02] px-6 py-16 text-center"><BookOpen className="mx-auto text-slate-600"/><p className="mt-4 text-slate-400">No posts found.</p></div></div>}<div className="mt-8 flex items-center gap-2">{Array.from({length:total},(_,i)=><button key={i} onClick={()=>setPage(i+1)} className={`h-9 min-w-9 rounded-lg border px-3 text-sm ${page===i+1?"border-emerald-500/50 bg-emerald-500/10 text-emerald-300":"border-white/10 text-slate-500"}`}>{i+1}</button>)}</div></div><aside className="hidden space-y-5 lg:block"><div className="rounded-2xl border border-white/10 bg-slate-900/40 p-6"><p className="font-mono text-[10px] uppercase tracking-[.25em] text-slate-500">CATEGORIES</p><div className="mt-4 space-y-2">{cats.slice(1).map(c=><button key={c} onClick={()=>setCat(c)} className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-sm text-slate-400 hover:bg-white/5 hover:text-white"><span>{c}</span><span>{posts.filter(p=>p.category===c).length}</span></button>)}</div></div><div className="rounded-2xl border border-white/10 bg-gradient-to-br from-emerald-500/10 to-transparent p-6"><p className="font-semibold text-white">Build less noise. Ship more signal.</p><p className="mt-2 text-sm leading-6 text-slate-400">The newsletter is where the useful notes end up.</p></div></aside></div></Container></main>}
