"use client";
import { useEffect,useState } from "react";
import { FileUp } from "lucide-react";
import type { FileRecord } from "@/types";
import { getFileRecords,saveFileMetadata,deleteFileRecord } from "@/lib/actions";
import { deleteFile } from "@/lib/storage";
import { AdminPageHeader,Panel } from "@/components/dashboard/AdminPrimitives";
import { FileUploader } from "@/components/dashboard/files/FileUploader";
import { FileGrid } from "@/components/dashboard/files/FileGrid";
import { Button } from "@/components/ui/Button";
export default function FilesPage(){const [files,setFiles]=useState<FileRecord[]>([]);const [uploading,setUploading]=useState(false);const load=async()=>setFiles(await getFileRecords() as FileRecord[]);useEffect(()=>{load().catch(()=>{})},[]);const onUpload=async(data:import("@/lib/storage").CloudinaryUploadResponse)=>{setUploading(true);try{await saveFileMetadata({publicId:data.public_id,secureUrl:data.secure_url,resourceType:data.resource_type,format:data.format,bytes:data.bytes,originalFilename:data.original_filename??"uploaded-file",folder:data.folder??"my-platform",width:data.width??undefined,height:data.height??undefined,createdAt:new Date()});await load()}finally{setUploading(false)}};return <div><AdminPageHeader eyebrow="MEDIA" title="File Manager" description="Manage media in Cloudinary while keeping metadata in Firestore." actions={<Button onClick={()=>document.getElementById("file-uploader")?.scrollIntoView({behavior:"smooth"})}><FileUp size={16}/> Upload</Button>}/><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_330px]"><Panel id="file-uploader" className="p-5"><h2 className="font-semibold text-white">Upload files</h2><p className="mt-1 text-xs text-slate-600">Signed uploads keep the API secret server-side.</p><div className="mt-5"><FileUploader onUpload={onUpload}/></div></Panel><Panel className="p-5"><p className="text-xs uppercase tracking-wider text-slate-600">STORAGE</p><p className="mt-2 text-4xl font-bold text-white">{files.length}</p><p className="mt-1 text-sm text-slate-500">files</p><p className="mt-8 text-xs uppercase tracking-wider text-slate-600">TOTAL BYTES</p><p className="mt-2 text-xl font-semibold">{(files.reduce((s,f)=>s+f.bytes,0)/1024/1024).toFixed(1)} MB</p>{uploading&&<p className="mt-8 text-xs text-emerald-300">Saving metadata…</p>}</Panel></div><div className="mt-8"><FileGrid files={files} onCopyUrl={f=>navigator.clipboard?.writeText(f.secureUrl)} onPreview={f=>window.open(f.secureUrl,"_blank","noopener,noreferrer")} onDelete={async f=>{if(confirm(`Delete ${f.originalFilename}?`)){await deleteFile(f.publicId,f.resourceType);await deleteFileRecord(f.id);load()}}}/></div></div>}
