"use server";
import { revalidatePath } from "next/cache";
import { FieldValue } from "firebase-admin/firestore";
import { adminAuth, adminDb } from "./firebase-admin";
import type { ContentItem, ContactSubmission, Lead, NewsletterSubscriber, Post, Project, SiteSettings, Transaction } from "@/types";
import { adminAdd, adminDelete, adminFind, adminGet, adminList, adminUpdate, serializeAdmin } from "./admin-db";
import { requireAdmin } from "./server-auth";
import { checkRateLimit } from "./rate-limit";
import { calculateReadTime, slugify } from "./utils";
import { defaultSiteSettings } from "./site-defaults";
const SETTINGS_ID="main";
export async function submitContactForm(formData:FormData){const name=String(formData.get("name")??"").trim();const email=String(formData.get("email")??"").trim().toLowerCase();const phone=String(formData.get("phone")??"").trim();const service=String(formData.get("service")??"Other").trim();const message=String(formData.get("message")??"").trim();if(!name||!email||!message)return{success:false,message:"Please fill the required fields."};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return{success:false,message:"Please provide a valid email address."};if(!(await checkRateLimit(`contact:${email}`,5,3600000)).allowed)return{success:false,message:"Too many submissions. Please try again later."};const id=await adminAdd("contact_submissions",{name,email,phone,service,message,status:"new",date:new Date()} as Omit<ContactSubmission,"id">);revalidatePath("/dashboard/contacts");return{success:true,message:"Message received.",id};}
export async function subscribeNewsletter(email:string,name=""){const normalized=email.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized))return{success:false,message:"Enter a valid email."};if(!(await checkRateLimit(`newsletter:${normalized}`,4,3600000)).allowed)return{success:false,message:"Please try again later."};const existing=await adminFind<NewsletterSubscriber>("newsletter","email",normalized);if(existing[0]){if(existing[0].status==="active")return{success:true,message:"You're already subscribed."};await adminUpdate<NewsletterSubscriber>("newsletter",existing[0].id,{status:"active"});return{success:true,message:"Welcome back."};}await adminAdd("newsletter",{email:normalized,name,status:"active",date:new Date()} as Omit<NewsletterSubscriber,"id">);revalidatePath("/dashboard/newsletter");return{success:true,message:"Subscribed successfully."};}
export async function trackPageViewServer(page:string,sessionId:string,userAgent:string,durationMs?:number){if(!page.startsWith("/")||page.length>200)return;await adminAdd("page_views",{page,sessionId,userAgent,timestamp:new Date(),durationMs});}
export async function getSiteSettings(){const data=await adminGet<SiteSettings>("site_settings",SETTINGS_ID);if(!data)throw new Error("Site settings have not been seeded yet.");const settings=serializeAdmin(data) as SiteSettings;return{...settings,siteVersion:settings.siteVersion??defaultSiteSettings.siteVersion};}
export async function updateSiteSettings(settings:Partial<SiteSettings>){await requireAdmin();await adminUpdate<SiteSettings>("site_settings",SETTINGS_ID,settings);for(const path of ["/","/about","/services","/portfolio","/blog","/contact"])revalidatePath(path);}
export async function resetSiteSettings(){await requireAdmin();const {defaultSettings}=await import("./seed");await adminDb.collection("site_settings").doc(SETTINGS_ID).set(defaultSettings,{merge:false});revalidatePath("/");}
export async function clearAppData(){await requireAdmin();const names=["posts","leads","projects","transactions","content_calendar","contact_submissions","newsletter","page_views","portfolio","files","services","testimonials","notifications"];for(const name of names){let lastId="";while(true){let query=adminDb.collection(name).orderBy("__name__").limit(400);if(lastId)query=query.startAfter(lastId);const snap=await query.get();if(snap.empty)break;const batch=adminDb.batch();for(const doc of snap.docs)batch.delete(doc.ref);await batch.commit();if(snap.size<400)break;lastId=snap.docs[snap.docs.length-1].id;}}}
export async function deleteAdminAccount(){const claims=await requireAdmin();await adminAuth.deleteUser(String(claims.uid));}
export async function getPosts(limit=100,category?:string){let posts=await adminList<Post>("posts");posts=posts.filter(p=>p.status==="published").sort((a,b)=>+new Date(b.publishedAt??b.createdAt)-+new Date(a.publishedAt??a.createdAt));if(category&&category!=="All")posts=posts.filter(p=>p.category===category);return serializeAdmin(posts.slice(0,limit)) as Post[];}
export async function getAllPosts(){await requireAdmin();return serializeAdmin(await adminList<Post>("posts")) as Post[];}
export async function getPostBySlug(slug:string){const posts=await adminFind<Post>("posts","slug",slug);return posts[0]?.status==="published"?serializeAdmin(posts[0]) as Post:null;}
export async function getPost(id:string){await requireAdmin();const p=await adminGet<Post>("posts",id);return p?serializeAdmin(p) as Post:null;}
export async function createPost(post:Omit<Post,"id">){await requireAdmin();const payload={...post,slug:post.slug||slugify(post.title),readTime:post.readTime||calculateReadTime(post.content),updatedAt:new Date()};const id=await adminAdd("posts",payload);revalidatePath("/blog");return id;}
export async function updatePost(id:string,post:Partial<Post>){await requireAdmin();await adminUpdate<Post>("posts",id,post);revalidatePath("/blog");}
export async function deletePost(id:string){await requireAdmin();await adminDelete("posts",id);revalidatePath("/blog");}
export async function getLeads(){await requireAdmin();return serializeAdmin(await adminList<Lead>("leads")) as Lead[];}export async function createLead(lead:Omit<Lead,"id">){await requireAdmin();return adminAdd("leads",lead);}export async function updateLead(id:string,lead:Partial<Lead>){await requireAdmin();await adminUpdate<Lead>("leads",id,lead);}export async function deleteLead(id:string){await requireAdmin();await adminDelete("leads",id);}
export async function getProjects(){await requireAdmin();return serializeAdmin(await adminList<Project>("projects")) as Project[];}export async function createProject(project:Omit<Project,"id">){await requireAdmin();return adminAdd("projects",project);}export async function updateProject(id:string,project:Partial<Project>){await requireAdmin();await adminUpdate<Project>("projects",id,project);}export async function deleteProject(id:string){await requireAdmin();await adminDelete("projects",id);}
export async function getTransactions(){await requireAdmin();return serializeAdmin(await adminList<Transaction>("transactions")) as Transaction[];}export async function createTransaction(transaction:Omit<Transaction,"id">){await requireAdmin();return adminAdd("transactions",transaction);}export async function updateTransaction(id:string,transaction:Partial<Transaction>){await requireAdmin();await adminUpdate<Transaction>("transactions",id,transaction);}export async function deleteTransaction(id:string){await requireAdmin();await adminDelete("transactions",id);}
export async function getContentCalendar(){await requireAdmin();return serializeAdmin(await adminList<ContentItem>("content_calendar")) as ContentItem[];}export async function createContentItem(item:Omit<ContentItem,"id">){await requireAdmin();return adminAdd("content_calendar",item);}export async function updateContentItem(id:string,item:Partial<ContentItem>){await requireAdmin();await adminUpdate<ContentItem>("content_calendar",id,item);}export async function deleteContentItem(id:string){await requireAdmin();await adminDelete("content_calendar",id);}
export async function getContactSubmissions(){await requireAdmin();return serializeAdmin(await adminList<ContactSubmission>("contact_submissions")) as ContactSubmission[];}export async function updateContactStatus(id:string,status:ContactSubmission["status"]){await requireAdmin();await adminUpdate<ContactSubmission>("contact_submissions",id,{status});}export async function deleteContactSubmission(id:string){await requireAdmin();await adminDelete("contact_submissions",id);}
export async function getNewsletterSubscribers(){await requireAdmin();return serializeAdmin(await adminList<NewsletterSubscriber>("newsletter")) as NewsletterSubscriber[];}export async function deleteNewsletterSubscriber(id:string){await requireAdmin();await adminDelete("newsletter",id);}
export async function getServices(){await requireAdmin();return serializeAdmin(await adminList("services"));}
export async function createService(service:Record<string,unknown>){await requireAdmin();return adminAdd("services",service);}
export async function updateService(id:string,service:Record<string,unknown>){await requireAdmin();await adminUpdate("services",id,service);revalidatePath("/");revalidatePath("/services");}
export async function deleteService(id:string){await requireAdmin();await adminDelete("services",id);revalidatePath("/");revalidatePath("/services");}
export async function getPortfolioItems(){return serializeAdmin(await adminList("portfolio"));}
export async function saveFileMetadata(data:Record<string,unknown>){await requireAdmin();return adminAdd("files",data);}export async function getFileRecords(){await requireAdmin();return serializeAdmin(await adminList("files"));}export async function deleteFileRecord(id:string){await requireAdmin();await adminDelete("files",id);}
export async function getDashboardSnapshot(){await requireAdmin();const [leads,projects,tx,contacts,posts]=await Promise.all([adminList<Lead>("leads"),adminList<Project>("projects"),adminList<Transaction>("transactions"),adminList<ContactSubmission>("contact_submissions"),adminList<Post>("posts")]);return serializeAdmin({leads,projects,tx,contacts,posts});}
