"use client";
import { useEffect,useMemo,useState } from "react";
import { ArrowDownLeft,ArrowUpRight,Plus,Wallet } from "lucide-react";
import { getProjects,getTransactions } from "@/lib/actions";
import type { Project,Transaction } from "@/types";
import { TransactionTable } from "@/components/dashboard/finance/TransactionTable";
import { TransactionModal } from "@/components/dashboard/finance/TransactionModal";
import { FinanceChart } from "@/components/dashboard/finance/FinanceChart";
import { Button } from "@/components/ui/Button";
import { StatCard } from "@/components/dashboard/StatCard";
export default function FinancePage(){const [tx,setTx]=useState<Transaction[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [modal,setModal]=useState(false);const load=()=>Promise.all([getTransactions(),getProjects()]).then(([a,b])=>{setTx(a);setProjects(b)});useEffect(()=>{load().catch(()=>{})},[]);const income=useMemo(()=>tx.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),[tx]);const expenses=useMemo(()=>tx.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0),[tx]);const outstanding=useMemo(()=>projects.reduce((s,p)=>s+Math.max(0,p.price-p.amountPaid),0),[projects]);const chart=useMemo(()=>{const m=new Map<string,{income:number;expenses:number}>();for(const t of tx){const d=new Date(t.date as unknown as string);const k=d.toLocaleDateString('en-US',{month:'short'});const x=m.get(k)||{income:0,expenses:0};x[t.type==='income'?'income':'expenses']+=t.amount;m.set(k,x)}return [...m.entries()].map(([month,v])=>({month,...v,net:v.income-v.expenses})).slice(-12)},[tx]);return <div><div className="flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-indigo-300">MONEY</p><h2 className="mt-2 text-3xl font-bold">Finance</h2></div><Button onClick={()=>setModal(true)}><Plus size={16}/> Add Transaction</Button></div><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard title="Total Income" value={income} icon={ArrowUpRight}/><StatCard title="Total Expenses" value={expenses} icon={ArrowDownLeft}/><StatCard title="Net Profit" value={income-expenses} icon={Wallet}/><StatCard title="Outstanding" value={outstanding} icon={Wallet}/></div><div className="mt-7 rounded-2xl border border-white/10 bg-slate-900/50 p-6"><h3 className="font-semibold">Monthly breakdown</h3><div className="mt-5"><FinanceChart data={chart}/></div></div><div className="mt-7"><TransactionTable transactions={tx} onChanged={load}/></div><TransactionModal isOpen={modal} onClose={()=>setModal(false)} onSaved={load}/></div>}
