import { NextResponse } from "next/server";
import { adminAdd,adminFind,adminUpdate } from "@/lib/admin-db";
import { checkRateLimit } from "@/lib/rate-limit";
import type { NewsletterSubscriber } from "@/types";
const emailRe=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const runtime="nodejs";
export async function POST(req:Request){try{const ip=(req.headers.get("x-forwarded-for")||"unknown").split(",")[0].trim();const rl=await checkRateLimit(`newsletter:${ip}`,10,60*60*1000);if(!rl.allowed)return NextResponse.json({error:"Too many requests. Please try later."},{status:429});const b=await req.json();const email=String(b.email||"").trim().toLowerCase(),name=String(b.name||"").trim();if(!emailRe.test(email))return NextResponse.json({error:"Enter a valid email."},{status:400});const found=await adminFind<NewsletterSubscriber>("newsletter","email",email);if(found[0]){if(found[0].status!=="active")await adminUpdate<NewsletterSubscriber>("newsletter",found[0].id,{status:"active"});return NextResponse.json({success:true,message:"You’re subscribed."})}await adminAdd("newsletter",{email,name,status:"active",date:new Date()} as Omit<NewsletterSubscriber,"id">);return NextResponse.json({success:true,message:"Subscribed successfully."})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to subscribe"},{status:500})}}
export async function DELETE(req:Request){try{const b=await req.json();const email=String(b.email||"").trim().toLowerCase();if(!emailRe.test(email))return NextResponse.json({error:"Invalid email."},{status:400});const found=await adminFind<NewsletterSubscriber>("newsletter","email",email);if(found[0])await adminUpdate<NewsletterSubscriber>("newsletter",found[0].id,{status:"unsubscribed"});return NextResponse.json({success:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to unsubscribe"},{status:500})}}
export async function GET(){try{const {adminList}=await import("@/lib/admin-db");const all=await adminList<NewsletterSubscriber>("newsletter");return NextResponse.json({count:all.filter(x=>x.status==="active").length})}catch{return NextResponse.json({count:0})}}
