"use client";
import { CalendarDays,List,Plus,Rows3 } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import type { Project,ProjectStatus } from "@/types";
import { getProjects,updateProject } from "@/lib/actions";
import { ProjectCard } from "@/components/dashboard/projects/ProjectCard";
import { ProjectModal } from "@/components/dashboard/projects/ProjectModal";
import { ProjectSidebar } from "@/components/dashboard/projects/ProjectSidebar";
import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
const cols:ProjectStatus[]=["pending","in_progress","review","delivered","paid","cancelled"];
const key=(d:Date)=>`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
export default function ProjectsPage(){
  const [projects,setProjects]=useState<Project[]>([]);const [view,setView]=useState("kanban");const [modal,setModal]=useState(false);const [edit,setEdit]=useState<Project|undefined>();const [selected,setSelected]=useState<Project|null>(null);const [month,setMonth]=useState(()=>new Date());const [calendarDay,setCalendarDay]=useState<Date|null>(null);
  const load=async()=>setProjects(await getProjects());useEffect(()=>{load()},[]);
  const move=async(p:Project,dir:number)=>{const i=cols.indexOf(p.status),next=cols[Math.min(cols.length-1,Math.max(0,i+dir))];if(next!==p.status){await updateProject(p.id,{status:next});load()}};
  const list=useMemo(()=>projects,[projects]);
  const monthCells=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();const cells:Array<Date|null>=Array.from({length:first.getDay()},()=>null);for(let d=1;d<=days;d++)cells.push(new Date(month.getFullYear(),month.getMonth(),d));while(cells.length%7)cells.push(null);return cells},[month]);
  const projectsForDay=(day:Date)=>projects.filter(p=>new Date(p.dateDue as unknown as string).toDateString()===day.toDateString());
  return <div>
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-indigo-300">OPERATIONS</p><h2 className="mt-2 text-3xl font-bold">Project Pipeline</h2></div><div className="flex gap-2"><div className="flex rounded-xl border border-white/10 bg-white/[.02] p-1">{[["kanban",Rows3],["list",List],["calendar",CalendarDays]].map(([k,I])=><button key={k as string} onClick={()=>setView(k as string)} className={`rounded-lg p-2 ${view===k?"bg-white/10 text-white":"text-slate-500"}`}><I size={16}/></button>)}</div><Button onClick={()=>{setEdit(undefined);setModal(true)}}><Plus size={16}/> New Project</Button></div></div>
    {view==="kanban"?<div className="mt-7 grid gap-4 xl:grid-cols-6">{cols.map(s=><div key={s} className="min-w-0"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold capitalize text-slate-400">{s.replaceAll("_"," ")}</span><span className="rounded-full bg-white/5 px-2 py-0.5 text-[10px] text-slate-500">{projects.filter(p=>p.status===s).length}</span></div><div className="min-h-[240px] space-y-3 rounded-2xl border border-white/5 bg-white/[.015] p-2">{projects.filter(p=>p.status===s).map(p=><ProjectCard key={p.id} project={p} onClick={()=>setSelected(p)} onMoveLeft={()=>move(p,-1)} onMoveRight={()=>move(p,1)}/>)}</div></div>)}</div>
    :view==="list"?<div className="mt-7 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-full text-sm"><thead className="bg-white/[.03] text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Client</th><th className="px-4 py-3">Project</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Progress</th><th/></tr></thead><tbody>{list.map(p=><tr key={p.id} className="border-t border-white/5"><td className="px-4 py-4 font-medium">{p.clientName}</td><td className="px-4 py-4 text-slate-400">{p.projectName}</td><td className="px-4 py-4 capitalize text-slate-400">{p.status.replaceAll("_"," ")}</td><td className="px-4 py-4">{p.price}</td><td className="px-4 py-4 text-slate-400">{new Date(p.dateDue as unknown as string).toLocaleDateString()}</td><td className="px-4 py-4"><div className="h-2 w-28 rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-500" style={{width:`${p.progress}%`}}/></div></td><td className="px-4 py-4"><button onClick={()=>setSelected(p)} className="text-xs text-emerald-300">Open</button></td></tr>)}</tbody></table></div>
    :<div className="mt-7 overflow-hidden rounded-2xl border border-white/10"><div className="flex items-center justify-between border-b border-white/10 bg-white/[.02] px-4 py-3"><button className="rounded-lg border border-white/10 px-3 py-1 text-sm text-slate-300" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>Previous</button><div className="text-sm font-semibold">{month.toLocaleString(undefined,{month:"long",year:"numeric"})}</div><button className="rounded-lg border border-white/10 px-3 py-1 text-sm text-slate-300" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>Next</button></div><div className="grid grid-cols-7 bg-white/[.03] text-center text-[10px] uppercase tracking-wider text-slate-600">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div key={x} className="py-3">{x}</div>)}</div><div className="grid grid-cols-7">{monthCells.map((day,i)=>day?<button key={i} onClick={()=>setCalendarDay(day)} className="min-h-28 border-t border-r border-white/5 p-2 text-left hover:bg-white/[.025]"><div className="text-xs text-slate-500">{day.getDate()}</div><div className="mt-2 space-y-1">{projectsForDay(day).slice(0,3).map(p=><div key={p.id} className="truncate rounded-md bg-indigo-500/10 px-2 py-1 text-[10px] text-indigo-200">{p.projectName}</div>)}{projectsForDay(day).length>3?<div className="text-[10px] text-slate-600">+{projectsForDay(day).length-3} more</div>:null}</div></button>:<div key={i} className="min-h-28 border-t border-r border-white/5 bg-black/10"/>)}</div></div>}
    <ProjectModal isOpen={modal} onClose={()=>setModal(false)} project={edit} onSaved={load}/>
    {calendarDay?<Modal title={`Projects due ${calendarDay.toLocaleDateString()}`} onClose={()=>setCalendarDay(null)}><div className="space-y-3">{projectsForDay(calendarDay).length?projectsForDay(calendarDay).map(p=><button key={p.id} onClick={()=>{setCalendarDay(null);setSelected(p)}} className="w-full rounded-xl border border-white/10 bg-white/[.02] p-4 text-left hover:bg-white/[.04]"><div className="font-semibold">{p.projectName}</div><div className="mt-1 text-xs text-slate-500">{p.clientName} · {p.status.replaceAll("_"," ")}</div></button>):<p className="text-sm text-slate-500">No projects are due on this date.</p>}</div></Modal>:null}
    {selected?<ProjectSidebar project={selected} onClose={()=>setSelected(null)} onUpdate={async patch=>{await updateProject(selected.id,patch);await load();setSelected({...selected,...patch} as Project)}}/>:null}
  </div>
}
